version: '3.8'
services:
  app:
    build: .
    image: employeemanagementsystems:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    container_name: employeemgmt-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:

