apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeemanagement-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employeemanagement-app
  template:
    metadata:
      labels:
        app: employeemanagement-app
    spec:
      containers:
        - name: employeemanagement-app
          image: employeemanagementsystems:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: employeemanagement-app-service
spec:
  type: NodePort
  selector:
    app: employeemanagement-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080

